export const endpoints = {
  GET_ORGANIZATION: '/api/organizations/:id',
  GET_ORGANIZATIONS: '/api/organizations',
  GET_PUBLIC_ORGANIZATIONS: '/api/public/organizations',
  GET_PUBLIC_ORGANIZATION_SLUG: '/api/public/organizations/find-one-by-slug/:slug',
  GET_PUBLIC_ORGANIZATION_ID: '/api/public/organizations/:id',
  POST_BACKGROUND_IMAGE_FROM_MEDIA: '/api/organizations/:id/background-image/create/:idMedia/from-media',
  POST_BACKGROUND_IMAGE: '/api/organizations/:id/background-image/create/:idMedia',
  POST_ADRESS_ORGANIZATION: '/api/organizations/:id/addresses',
  POST_CREATE_ORGANIZATION: '/api/organizations',
  POST_CREATE_ORGANIZATION_SUGGEST: '/api/organizations/suggest',
  POST_CREATE_ORGANIZATION_REGISTER: '/api/organizations/register',
  POST_CREATE_ORGANISATION_PERSON: '/api/organizations/register-to-person',
  POST_KYC: '/api/organizations/:id/kycs',
  POST_RIB: '/api/organizations/:id/rib',
  POST_EMPLOYEE: '/api/organizations/:id/employees',
  POST_FOUNDER: '/api/organizations/:id/founders',
  POST_HOURS_ORGANIZATION: '/api/organizations/:idOrganization/opening-hours-specification',
  POST_PICTURE_ORGANIZATION_FROM_MEDIA: '/api/organizations/:id/pictures/:idMedia/from-media',
  POST_PICTURE_ORGANIZATION:'/api/organizations/:id/pictures/:idMedia',
  POST_LOGO_ORGANIZATION: '/api/organizations/:id/logo/create/:idMedia',
  POST_COMMUNICATION_ORGANIZATION: '/api/organizations/:id/communication',
};
