export const endpoints = {
  GET_ME: '/api/persons/me',
  GET_ONE_BY_USERID: '/api/persons/:id',
  GET_POSITION: '/api/persons/current-address',
  GET_PERSONS: '/api/persons',
  GET_CONFIG: '/api/persons/config',
  GET_VIRTUAL_MONEY: '/api/people/virtual-money',
  POST_ADDRESS: '/api/Rpersons/addresses',
  POST_FAVORITE_ORG: '/api/persons/:idPerson/organization/:idOrganization/favorite/add',
  POST_PICTURE: '/api/persons/:idPerson/picture/create/:idMedia',
  POST_CREATE_PERSON: '/api/persons',
  POST_CREATE_ADMIN: '/api/persons/super-admin',
  POST_REGISTER_EMAIL_PASSWORD: '/api/persons/register-with-email-and-password',
  POST_REFRESH_IAM: '/api/user/people/iam/refresh',
  POST_REFRESH_IAM_TO_ONE: '/api/user/people/iam/refresh/:id',
  POST_ENABLE: '/api/persons/:id/enable',
  POST_DISABLED: '/api/persons/:id/disable',
  POST_LEGAL_NOTICE: '/api/persons/:id/legal-notice',
  POST_PRIVACY_POLICY: '/api/persons/:id/privacy-policy',
  POST_ADD_BLACK_LIST: '/api/persons/:id/add-to-black-list',
};
